### ISSUE TITLE
Undefined variable: label

### ISSUE THREAD

**Issue by ChrisMoutsos** [tanoconsulting/ezmigrationbundle2#10]
I got this error:

```
Migration failed! Reason: Error in execution of step 2: Notice: Undefined variable: label in file /app/vendor/tanoconsulting/ezmigrationbundle2/Core/EventListener/TracingStepExecutedListener.php line 143
```

It looks like `$label` just needs to be set to `''` by default. On main branch, when running a migration.

**Comment by gggeek** [comment]
Fixed in https://github.com/tanoconsulting/ezmigrationbundle2/releases/tag/1.0.0-ALPHA2
