### ISSUE TITLE
Undefined class InvalidStepDefinitionExceptionn (typo)

### ISSUE THREAD

**Issue by spidey89** [tanoconsulting/ezmigrationbundle2#11]
In Kaliop\eZMigrationBundle\Core\Executor\ContentTypeManager.php line 53:

`throw new InvalidStepDefinitionExceptionn("The '$key' key is missing in a content type creation definition");`

but the imported class is: `use Kaliop\eZMigrationBundle\API\Exception\InvalidStepDefinitionException;`
(double 'n' at the end)

I think it's just a typo

**Comment by gggeek** [comment]
Thx. Fixed, will be in the next alpha/beta release
