### ISSUE TITLE
Support eZPlatform 4

### ISSUE THREAD

**Issue by gggeek** [tanoconsulting/ezmigrationbundle2#19]
This seems a though one, as all namespaces, config keys, REST API routes have been renamed in the transition of eZPlatform from v3 to v4.

Worth of note as well is that eZPlatform 4 has its own migration stuff, heavily inspired by Kaliop Migration Bundle but nonetheless incompatible with it, which makes this bundle more or less a useless duplicate

**Comment by McLone** [comment]
Actually, if I’m not wrong, ibexa/migrations, which came with Ibexa 3, is not available for the open source version : your bundle is still pertinent for us and work nicely with 3.3. ❤️
…But, indeed, an Ibexa 4 compatible version might need an ezmigrationbundle3 😅

**Comment by gggeek** [comment]
Lol, it seems someone already started on the Ibexa DXP 4 port... see:

https://github.com/wizhippo/ibexa-migration-bundle

**Comment by gggeek** [comment]
Will be implemented in https://github.com/tanoconsulting/ibexa-migration-bundle.

Thanks again to @wizhippo!
