### ISSUE TITLE
Rename default Migrations folder

### ISSUE THREAD

**Issue by gggeek** [tanoconsulting/ezmigrationbundle2#2]
See discussion at https://github.com/kaliop-uk/ezmigrationbundle/issues/101

To avoid conflicts with Doctrine migrations, we could probably go for `MigrationsDefinitions` over `Migrations`

**Comment by gggeek** [comment]
Slightly related: make the same dir in the src/ dir be looped over too

**Comment by sklimaszewski** [comment]
The change is included in PR #9

**Comment by gggeek** [comment]
Thx Stan
