### ISSUE TITLE
The 'admin-login' option is ignored

### ISSUE THREAD

**Issue by jlecocq** [tanoconsulting/ezmigrationbundle2#27]
Hello :)

I'm working on a project in which the 'admin' user has been removed and I've realized the --admin-login option didn't work when using the command : 
`php bin/console kaliop:migration:migrate --admin-login=customlogin`

To fix this issue, there just need to change the line 351 of the file Core/MigrationService.php to use the `'adminUserLogin'` key instead of `'adminLogin'` (The different commands define a key `'adminUserLogin'` in the $migrationContext array).

I you could commit this fix it would be perfect, thank you ! :)

**Comment by gggeek** [comment]
Hello. I'll take a look at this tomorrow.

Pull requests are also welcome, of course - ideally accompanied by a new unit test ;-)

**Comment by gggeek** [comment]
Should be fixed in 1.0.5
